module:
  imports:
    # Any Hugo modules you installed will appear here.
  
    # Add the Wowchemy CMS module below, if it has not already been added:
    - path: github.com/wowchemy/wowchemy-hugo-themes/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-themes/wowchemy/v5
